### ISSUE TITLE
console output is confusing and too long and when starting REMIND runs

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#1001]
When a REMIND run is started on console, renv fills the output on the screen with logs that are hundreds of lines long and difficult to understand, with expressions like e.g. `* The project is already synchronized with the lockfile.`. What does this actually mean?

**Comment by mikapfl** [comment]
I think this is already worked on in #998

**Comment by giannou** [comment]
it is indeed. thanks! any idea what the project message means?

**Comment by pfuehrlich-pik** [comment]
The renv.lock file documents which package versions are installed in the renv. After a package was updated, the package library contains the new package version, but the lockfile still has an entry with the old version number, so they are out of sync. The message is the result of a successful check whether project library and lockfile are in sync.

**Comment by giannou** [comment]
ok, thanks for the explanation! I would suggest to add this to the renv tutorial (if not already there) and change the message (if it's not a standard renv message that cannot be changed of course) to something more understandable like ` * The renv lockfile is synchronized with your project's R library.`

**Comment by pfuehrlich-pik** [comment]
I decided to suppress the message (it's a default renv message), because there is a check right after the message, and there is a more verbose error if the project library and lockfile are out of sync.
