### ISSUE TITLE
Structure of main.gms (rather lack thereof)

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1017]
I'm trying to find the right spot to put a new a compile-time variable related to the industry module.  I used to put them in the vicinity of other variables of the module, but that fails right now.
For example, `cm_steel_secondary_max_share_scenario` is mentioned three times in `main.gms` currently.  Two times with some documentation, and once the actual definition, but without documentation. 

https://github.com/remindmodel/remind/blob/847a0fb21e80043f14f60146dd2f8accdeaf3617/main.gms#L1280-L1283

https://github.com/remindmodel/remind/blob/847a0fb21e80043f14f60146dd2f8accdeaf3617/main.gms#L1374-L1376

https://github.com/remindmodel/remind/blob/847a0fb21e80043f14f60146dd2f8accdeaf3617/main.gms#L1609-L1612

1. Is there a process for cleaning that up in some form?
2. Is there a structure of where to put stuff?  Or do I just drop it anywhere now?

**Comment by LaviniaBaumstark** [comment]
I hoped that part of this cleaning could happen yesterday. In general, right next to a parameter or flag there should be the documentation, starting with `*'`to be interpreted by goxygen. The current documentation is based on what I found in default.cfg and main.gms and merging with the developments in the default branch. So, there is much to improve. If you (and other industry people) could take care of the industry switches, that would be great

**Comment by LaviniaBaumstark** [comment]
and you find examples for documentation at the beginning of each part: modules, parameters, flags
