### ISSUE TITLE
Redo industry production fixing

### ISSUE THREAD

**Issue by pweigmann** [remindmodel/remind#1033]
As discussed [here](https://github.com/remindmodel/remind/pull/1000#discussion_r993531227) in #1000, find a better way to fix production targets than by fixing `vm_cesIO`.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> As discussed [here](https://github.com/remindmodel/remind/pull/1000#discussion_r993531227) in #1000, find a better way to fix production targets than by fixing `vm_cesIO`.

You'll have to be more specific than that.
https://github.com/pweigmann/remind/blob/528e563d17acf13c67d8800c4d253eae94ffd0f9/modules/37_industry/subsectors/datainput.gms#L277-L364
Under which circumstances are you fixing these quantities?  Baseline or policy scenarios?  Baseline _and_ policy scenarios?
