### ISSUE TITLE
output.R reselect output directories fails

### ISSUE THREAD

**Issue by rauner** [remindmodel/remind#1059]
<pre>Type &apos;<font color="#26A269">y</font>&apos; to continue, &apos;<font color="#12488B">r</font>&apos; to reselect output directories, &apos;<font color="#C01C28">n</font>&apos; to abort: 
r

<font color="#C01C28">Stopping execution now.</font>

Error in eval(exprs[i], envir) : Couldn&apos;t find choosefolder() function
Warning message:
Script policyCosts.R was stopped by an error and not executed properly!</pre>

**Comment by orichters** [comment]
Should already be fixed with https://github.com/remindmodel/remind/pull/1049

**Comment by mikapfl** [comment]
@rauner can you check if it happens again and/or share the commit of the remind repo you are working at (e.g. `git log`)?

**Comment by rauner** [comment]
commit 363c55d17a7b8715e4b195d0466d33421fc59573 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Sebastian Rauner <rauner@pik-potsdam.de>
Date:   Mon Oct 17 10:53:15 2022 +0200

    add higher bioenergy RC scenario

commit b2b5fff64a537c214b9d8e43949cd56da659561e
Author: Sebastian Rauner <rauner@pik-potsdam.de>
Date:   Mon Oct 17 10:44:15 2022 +0200

    add babysit gdxes

**Comment by rauner** [comment]
works :)
