### ISSUE TITLE
comparescenarios2 fails with latex compilation error

### ISSUE THREAD

**Issue by rauner** [remindmodel/remind#1067]
/p/system/packages/pandoc/2.14.2/bin/pandoc +RTS -K512m -RTS /p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/compScen-SHAPE-2022-11-11_11.47.28-REMIND-MAgPIE/cs2_main.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output /p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/compScen-SHAPE-2022-11-11_11.47.28-REMIND-MAgPIE/compScen-SHAPE-2022-11-11_11.47.28-REMIND-MAgPIE.tex --lua-filter /p/projects/rd3mod/R/libraries/snapshots/2022_10_14_R4/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /p/projects/rd3mod/R/libraries/snapshots/2022_10_14_R4/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --table-of-contents --toc-depth 6 --template cs2_latex_template.tex --number-sections --highlight-style tango --pdf-engine pdflatex --include-in-header cs2_pdf_header_include.tex --include-in-header /tmp/RtmpjWy9ra/rmarkdown-str2e8054d6831b.html 
Error:
! LaTeX failed to compile /p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/compScen-SHAPE-2022-11-11_11.47.28-REMIND-MAgPIE/compScen-SHAPE-2022-11-11_11.47.28-REMIND-MAgPIE.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
Backtrace:
     x
  1. \-global run_compareScenarios2(outputDirs, outFileName, profileName)
  2.   +-base::do.call(compareScenarios2, args)
  3.   \-remind2 (local) `<fn>`(...)
  4.     \-rmarkdown::render(...)
  5.       \-rmarkdown:::latexmk(...)
  6.         \-tinytex::latexmk(file, engine, if (biblatex) "biber" else "bibtex")
  7.           \-tinytex:::latexmk_emu(...)
  8.             \-tinytex (local) run_engine()
  9.               +-tinytex:::system2_quiet(...)
 10.               \-tinytex (local) on_error()
 11.                 \-tinytex:::show_latex_error(file, logfile)
Execution halted

**Comment by rauner** [comment]
/piam/SHAPE_runs/coupled_2022-10-17/remind/compScen-SHAPE-2022-11-11_11.47.28-REMIND-MAgPIE

**Comment by rauner** [comment]
Robert mentioned that he was able to work around by copying an older comparescenarios but did not help in my case:

_And interestingly, when there were problems with cs2 in the past, I was able to simply copy the "scripts" folder (or even only the "cs2" folder from within "scripts", can't remember) to the not-working REMIND instance, and then everything worked fine.
[3:03 PM](https://mattermost.pik-potsdam.de/rd3/pl/petwqjsihffrfe5ngqrfe6nfir)

so you might try that as a simple workaround_

**Comment by mikapfl** [comment]
What exactly were you trying to run? `start.R output.R` and then comparing which scenarios?

**Comment by mikapfl** [comment]
If I run it on a compute node in an interactive session (start with `srun --qos priority --pty bash`, then run `R`), it works. I used this command in the corresponding folder (`/p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/compScen-mikapfl-2022-12-05_13.56.19-default`):
```R
r$> remind2::compareScenarios2(
        mifScen = c("/p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/output/C_SSP2EU-PkBudg650-rem-2/REMIND_generic_C_SSP2EU-PkBudg650-rem-2.
    mif", "/p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/output/C_SSP2EU-PkBudg650-rem-3/REMIND_generic_C_SSP2EU-PkBudg650-rem-3.mif"),
        mifHist = "/p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/output/C_SSP2EU-PkBudg650-rem-2/historical.mif",
        cfgScen = c("/p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/output/C_SSP2EU-PkBudg650-rem-2/config.Rdata", "/p/projects/piam/SHAPE_r
    uns/coupled_2022-10-17/remind/output/C_SSP2EU-PkBudg650-rem-3/config.Rdata"),
        cfgDefault = "/p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/config/default.cfg",
        outputDir = "/p/projects/piam/SHAPE_runs/coupled_2022-10-17/remind/compScen-mikapfl-2022-12-05_13.56.19-default",
        outputFile = "compScen-mikapfl-2022-12-05_13.56.19-default.pdf",
        outputFormat = "pdf"
      )
```
Maybe that's an option for you, too? Or maybe you can check if the generated pdf is generally what you want? I've never used cs2 so it is a bit difficult for me to debug this, especially if it is a heisenbug which goes away if I start measuring.

**Comment by rauner** [comment]
That works, thanks a lot
