### ISSUE TITLE
toolReportEDGET introduces duplicated variables

### ISSUE THREAD

**Issue by dklein-pik** [remindmodel/remind#1073]
The EDGET reporting (`toolReportEDGET`) adds variables to the output of `convGDX2MIF` that are already there:
```
 [1] "ES|Transport|Pass"                "ES|Transport|Freight"
 [3] "FE|Transport|Pass"                "FE|Transport|Freight"
 [5] "FE|Transport|Pass|Liquids"        "FE|Transport|Pass|Hydrogen"
 [7] "FE|Transport|Pass|Gases"          "FE|Transport|Pass|Electricity"
 [9] "FE|Transport|Freight|Liquids"     "FE|Transport|Freight|Hydrogen"
[11] "FE|Transport|Freight|Gases"       "FE|Transport|Freight|Electricity"
```
Additional duplicates are introduced by applying `remind2::deletePlus` on the EDGET output:
```
[1] "FE|Transport"             "FE|Transport|Liquids"
[3] "FE|Transport|Hydrogen"    "FE|Transport|Gases"
[5] "FE|Transport|Electricity"
```
since the original mif from `convGDX2MIF` has the following variables of which the `+` get removed, making them duplicates of the variables added by the EDGET reporting:
```
FE|++|Transport
FE|Transport|+|Electricity
FE|Transport|+|Gases
FE|Transport|+|Hydrogen
FE|Transport|+|Liquids
```

**Comment by dklein-pik** [comment]
Here is a function to find the duplicated variables in a mif file. Possibly quitte or dplyr or other packages provide their own functions to test this that I don't know about.
``` R
    du <- function(path_to_mif) {
      mifData <- read.csv(path_to_mif, sep = ";", check.names = FALSE)
      b <- subset(mifData, Region == "CAZ", select = Variable)
      b <- b$Variable
      if (any(duplicated(b))) return(b[duplicated(b)])
    }
```

**Comment by johannah-pik** [comment]
Hi David! Thank you for pointing that out and sorry for the inconvenience caused. I will think of a solution to name the variables provided by the EDGE-T reporting function differently. We have to change some of the plotting scripts then as well. Is that super urgent right now?

**Comment by dklein-pik** [comment]
Hi Johanna, for me it is not super urgent, but I cannot really judge because I am currently not involved in projects that rely on the reporting.

**Comment by orichters** [comment]
Is it possible that the double variables are also responsible for these weird looking patterns in compare Scenarios?

![image](https://user-images.githubusercontent.com/90761609/203742388-be370432-8b66-4daf-93d1-6d41301654e4.png)

**Comment by dklein-pik** [comment]
It very likely looks like it, because it only affects the transport sector.

**Comment by orichters** [comment]
I guess Alois just likes Bavaria…
![image](https://user-images.githubusercontent.com/90761609/203746525-c43e0ee3-78f3-418b-8337-2ce44c56f11c.png)

**Comment by dklein-pik** [comment]
This is terrific!

**Comment by johannah-pik** [comment]
https://github.com/pik-piam/edgeTransport/pull/206 this PR should fix the problem with the duplicates for now- in the long term, we plan to give all variables reported by EDGET a unique naming scheme
