### ISSUE TITLE
EUR 2020 Electricity Spike

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1085]
As of #997, `EUR` shows a pronounced spike in electricity usage in 2020 in both normal and calibration runs.

**Comment by robertpietzcker** [comment]
There is an equation q32_elh2VREcapfromTestor in 32_power/IntC that requires that elh2 is built once storage technologies are required. 

with Felix' commit, he forbid 2020 elh2 investment, meaning that the share of VRE had to be pushed below 7% (that is when storage requirements kick in). 

This was achieved by increasing total usableSE production such that at a given VRE capacity (forced in by 2020 bounds), the share of this VRE was below 7 %.

disabling this equation should remove the problem. 
It will also likely strongly reduce electrolysis build-up, as it is (after removing the equation) only driven by prices, but that remains to be seen.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
For testing, I just disabled the equation completely
```
q32_elh2VREcapfromTestor(t,regi)$( NO ) ..
```
Should we disable it for only the "no `elh2`" period instead?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Is there still any need for `elh2VRE`?
https://github.com/remindmodel/remind/blob/14d7b1245acd4e57fb52fb845d00a459383dd4e2/modules/32_power/IntC/bounds.gms#L76-L77

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Closed by #1099.
