### ISSUE TITLE
pcc, pco still exist in vm_emiTeDetail, breaking remind2 reporting

### ISSUE THREAD

**Issue by orichters** [remindmodel/remind#1088]
[This line](https://github.com/pik-piam/remind2/blob/55b2cc5901b983b61e1ba2b183e35765da1cc2d4/R/reportLCOE.R#L306-L308) in reportLCOE fails with
```
Error in .dimextract(x, k, 3, pmatch = pmatch) : 
  subscript out of bounds ("pcc", "pco")
```
This wasn't the solution: https://github.com/remindmodel/remind/pull/1087

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> [This line](https://github.com/pik-piam/remind2/blob/55b2cc5901b983b61e1ba2b183e35765da1cc2d4/R/reportLCOE.R#L306-L308) in reportLCOE fails with
> 
> ```
> Error in .dimextract(x, k, 3, pmatch = pmatch) : 
>   subscript out of bounds ("pcc", "pco")
> ```

Can't replicate.  Which .gdx does this fail on?

**Comment by orichters** [comment]
`/p/tmp/oliverr/NGFS_v3_tests/2022-11-10/remind/output/d_rap_bIT_2022-11-15_09.17.30/fulldata.gdx`
Although I'm not totally sure whether this may have been caused by fixing the run on a run that did not contain the deletion of `pco`. If you can't replicate, it is probably fine. I will rerun the whole cascade and see whether the problem persists.

**Comment by orichters** [comment]
Indeed. Well, than: thanks, I think we can close here.
