### ISSUE TITLE
Improve testing suit

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1119]
See #1111
For now a place to note down thought on that.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
- Output should be cleaner.  Need to figure out how the different reporters operate.  The brute-force option would be to capture/suppress all messages/warning/errors, use `test_dir('./tests/testthat/', reporter = 'list', stop_on_failure = FALSE)` and parse the results manually to provide proper output.

**Comment by fschreyer** [comment]
I this error message for having a testOneRegi run with infeasibilities. Error message could be improved. 

```
Failure (test_03-quick.R:11:3): start.R config/tests/scenario_config_quick.csv works
`status` not equal to 0.
1/1 mismatches
[1] 1 - 0 == 1
Backtrace:
 1. expectSuccessStatus(output)
      at test_03-quick.R:11:2
 2. testthat::expect_equal(status, 0)
      at tests/testthat/helper_skipFailed.R:14:4
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Error message could be improved.

Not really.  The `testthat` package is not really designed for testing arbitrary code that just happens to be called from within R.  All reporters provided with the package either show the rather unhelpful "1 &ne; 0", or they show nothing at all.
