### ISSUE TITLE
broken fixing of industry to exogenous scenarios

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1156]
https://github.com/remindmodel/remind/blob/bdc79cd00e7d920c1bb6bc6e9225e2a4b51692d6/modules/37_industry/subsectors/bounds.gms#L65
doesn't work, because there are not logical conjunctions (`AND`, `OR`) for dollar-conditions.  The block of code gets straight-out ignored.

@pweigmann this code came here via #1000.  Can you check if any runs from there are affected by this?  `$ dumpgdx fulldata.gdx vm_cesIO "DEU,ue_.*UP\>"` should show fixings for things other than `ue_steel_secondary` after `2005` (but I expect it not to).

**Comment by mikapfl** [comment]
Should we add something to codeCheck or so, to avoid this happening again? It is pretty stupid of GAMS to flat-out ignore logical conjunctions (in some cases - if the first part of an `or` is false, the block is ignored, if the first part of an `or` is true, it is a compilation error) and I see the potential for nasty bugs.

**Comment by pweigmann** [comment]
> @pweigmann this code came here via #1000. Can you check if any runs from there are affected by this? `$ dumpgdx fulldata.gdx vm_cesIO "DEU,ue_.*UP\>"` should show fixings for things other than `ue_steel_secondary` after `2005` (but I expect it not to).

Indeed, the fixings as defined [here](https://github.com/remindmodel/remind/blob/bdc79cd00e7d920c1bb6bc6e9225e2a4b51692d6/modules/37_industry/subsectors/datainput.gms#L345) don't show up in a current run (`/p/tmp/pascalwe/ariadne/production/remind_22-12-14_ap_emiTargetFix/output/EnSec_2023-01-06_15.00.50`). Only upper bounds until 2020 are set for things other than `ue_steel_secondary`. Will fix it for the next run.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Should we add something to codeCheck or so, to avoid this happening again? It is pretty stupid of GAMS to flat-out ignore logical conjunctions (in some cases - if the first part of an `or` is false, the block is ignored, if the first part of an `or` is true, it is a compilation error) and I see the potential for nasty bugs.

If you can whip something up …
Seems like a veritable quagmire to me, parsing GAMS dollar-statements and distinguishing them from valid GAMS code on the same line. 

This appears to have happened only once in almost 16 years of REMIND, so maybe @Renato-Rodrigues just tells newcomers not to do that (or to use Stephen's workaround) and we let it rest?

I used `$ ag "^[\$]ifthen.*\b(and|or)\b"`, which turned up one  true and two false positives:
```
modules/31_fossil/MOFEX/equations.gms
127:$ifthen.cm_oil_scen %cm_oil_scen% == "highOil"	 +(10)$(cm_startyear eq 2015 AND pm_ttot_val(ttot+1) eq 2015 AND ((sameas(enty,"peoil") AND sameas(rlf,"7")) OR (sameas(enty,"pegas") AND sameas(rlf,"6"))))

modules/31_fossil/timeDepGrades/equations.gms
180:$ifthen.cm_oil_scen %cm_oil_scen% == "highOil"	 +(10)$(cm_startyear eq 2015 AND pm_ttot_val(ttot+1) eq 2015 AND ((sameas(enty,"peoil") AND sameas(rlf,"7")) OR (sameas(enty,"pegas") AND sameas(rlf,"6"))))

modules/37_industry/subsectors/bounds.gms
65:$ifthen.policy_scenario (("%cm_indstExogScen%" == "forecast_bal") OR ("%cm_indstExogScen%" == "forecast_ensec"))   !! cm_indstExogScen
```
One could rule that `$ifthen` statements must to be on a separate line (better anyway), but for `$if` statements this breaks just down
```
$ ag "^[\$]if.*\b(and|or)\b"
modules/05_initialCap/on/preloop.gms
423:$if %cm_techcosts% == "GLO"   loop(ttot$((ttot.val le 2030) AND (ttot.val ge 2005)),
424:$if %cm_techcosts% == "GLO"     loop(te$( teEtaIncr(te) AND (sameas(te,"pc") OR sameas(te,"ngt") OR  sameas(te,"ngcc") ) ),
428:$if %cm_techcosts% == "GLO"   loop(ttot$((ttot.val le 2050) AND (ttot.val ge 2005)),
429:$if %cm_techcosts% == "GLO"     loop(te$(teEtaConst(te) AND ( sameas(te,"pc") OR sameas(te,"ngt") OR  sameas(te,"ngcc") ) ),

modules/02_welfare/utilitarian/equations.gms
36:$if "%cm_INCONV_PENALTY_FESwitch%" == "on"  - sum((entySe,entyFe,te,sector,emiMkt)$(se2fe(entySe,entyFe,te) AND entyFe2Sector(entyFe,sector) AND sector2emiMkt(sector,emiMkt) AND (entySeBio(entySe) OR entySeSyn(entySe) OR entySeFos(entySe)) ), v02_NegInconvPenFeBioSwitch(ttot,regi,entySe,entyFe,sector,emiMkt) + v02_PosInconvPenFeBioSwitch(ttot,regi,entySe,entyFe,sector,emiMkt))/1e3	

modules/02_welfare/ineqLognormal/equations.gms
40:$if "%cm_INCONV_PENALTY_FESwitch%" == "on"  - sum((entySe,entyFe,te,sector,emiMkt)$(se2fe(entySe,entyFe,te) AND entyFe2Sector(entyFe,sector) AND sector2emiMkt(sector,emiMkt) AND (entySeBio(entySe) OR entySeSyn(entySe) OR entySeFos(entySe)) ), v02_NegInconvPenFeBioSwitch(ttot,regi,entySe,entyFe,sector,emiMkt) + v02_PosInconvPenFeBioSwitch(ttot,regi,entySe,entyFe,sector,emiMkt))/1e3	

modules/31_fossil/MOFEX/equations.gms
127:$ifthen.cm_oil_scen %cm_oil_scen% == "highOil"	 +(10)$(cm_startyear eq 2015 AND pm_ttot_val(ttot+1) eq 2015 AND ((sameas(enty,"peoil") AND sameas(rlf,"7")) OR (sameas(enty,"pegas") AND sameas(rlf,"6"))))

modules/31_fossil/timeDepGrades/equations.gms
180:$ifthen.cm_oil_scen %cm_oil_scen% == "highOil"	 +(10)$(cm_startyear eq 2015 AND pm_ttot_val(ttot+1) eq 2015 AND ((sameas(enty,"peoil") AND sameas(rlf,"7")) OR (sameas(enty,"pegas") AND sameas(rlf,"6"))))

modules/37_industry/subsectors/bounds.gms
65:$ifthen.policy_scenario (("%cm_indstExogScen%" == "forecast_bal") OR ("%cm_indstExogScen%" == "forecast_ensec"))   !! cm_indstExogScen

modules/30_biomass/magpie_40/datainput.gms
40:$if %cm_MAgPIE_coupling% == "on"  table p30_pebiolc_pricemag_coupling(tall,all_regi)     "prices and costs for 2nd gen. purpose grown bioenergy from MAgPIE"

core/datainput.gms
216:$if not "%cm_inco0RegiFactor%" == "off" p_inco0(ttot,regi,te)$(p_inco0(ttot,regi,te) and p_new_inco0RegiFactor(te)) = p_new_inco0RegiFactor(te)*p_inco0(ttot,regi,te);
1392:$if %cm_MAgPIE_coupling% == "off" parameter f_macBaseMagpie(tall,all_regi,all_enty,all_LU_emi_scen,all_rcp_scen)    "baseline emissions of N2O and CH4 from landuse based on data from Magpie"
1393:$if %cm_MAgPIE_coupling% == "on"  parameter f_macBaseMagpie_coupling(tall,all_regi,all_enty)                        "baseline emissions of N2O and CH4 from landuse based on data from Magpie"

core/bounds.gms
363:$ifi %optimization% == "negishi" if( (cm_startyear le 2010 AND cm_emiscen > 1), vm_emiAllGlob.fx('2010','co2') = 8.9 + 1.46; ); !! 8.9 is fossil emissions + cement, 1.4 land use
```
