### ISSUE TITLE
Wrong / outdated parameters in scenario configs.

### ISSUE THREAD

**Issue by mikapfl** [remindmodel/remind#1157]
Probably related to the code cleaning, we have quite a lot of scenario configs with wrong or outdated parameters, which will be ignored in new REMIND runs. Thanks to @orichters for writing the necessary code to find that out cleanly!

Affected scenario configs and parameters are:

* `scenario_config_DeepEl.csv`:
   - [x] `cm_buildings_scen`: https://github.com/remindmodel/remind/pull/1174
* `scenario_config_EDGE-T_NDC_NPi_pkbudget.csv`
   - [x] `cm_shSynTrans`: https://github.com/remindmodel/remind/pull/1169
* `scenario_config_GCS.csv`:
   - [x] `cm_CO2priceRegConvYr`: https://github.com/remindmodel/remind/pull/1174
   - [x] `cm_INCONV_PENALTY_bioSwitch`: https://github.com/remindmodel/remind/pull/1168
* `scenario_config_NAVIGATE_300.csv`:
   - [x] `cm_bioenergy_tax`: 
   - [x] `cm_bioprod_histlim`: https://github.com/remindmodel/remind/pull/1184
   - [x] `cm_BioImportTax_EU`: https://github.com/remindmodel/remind/pull/1184
   - [x] `c_BaselineAgriEmiRed`: https://github.com/remindmodel/remind/pull/1184
   - [x] `cm_ariadne_VRECapFac_adj`: https://github.com/remindmodel/remind/pull/1184
   - [x] `cm_OILRETIRE`: https://github.com/remindmodel/remind/pull/1174
* `21_regions_EU11/scenario_config_21_EU11_ARIADNE.csv`:
   - [x] `cm_biotrade_phaseout`
* `21_regions_EU11/scenario_config_21_EU11_ECEMF.csv`:
   - [x] `cm_bioprod_histlim`: https://github.com/remindmodel/remind/pull/1184
   - [x] `cm_BioImportTax_EU`: https://github.com/remindmodel/remind/pull/1184
   - [x] `cm_build_costDecayStart` https://github.com/remindmodel/remind/pull/1169
   - [x] `cm_shSynTrans`
* `21_regions_EU11/scenario_config_21_EU11_Fit_for_55_sensitivity.csv`:
   - [x] `cm_bioprod_histlim`
   - [x] `cm_BioImportTax_EU`: https://github.com/remindmodel/remind/pull/1184
   - [x] `cm_build_costDecayStart`: https://github.com/remindmodel/remind/pull/1169
   - [x] `cm_shSynTrans`: https://github.com/remindmodel/remind/pull/1169

Please check if you touched the corresponding parameter in the code cleaning or feel responsible for the scenario config and fix this by proper renaming / dropping / using other parameters as appropriate.

**Comment by pweigmann** [comment]
Thanks for the overview! Working on updating `21_regions_EU11/scenario_config_21_EU11_ARIADNE.csv` anyway, will fix it accordingly.

**Comment by merfort** [comment]
Thanks! Im [PR1054](https://github.com/remindmodel/remind/pull/1054) I am already dealing with `cm_bioenergy_tax` and `cm_biotrade_phaseout` in the respective files.

**Comment by orichters** [comment]
@pweigmann, @merfort: Please either wait until #1123 is merged, or make a pull request against https://github.com/mikapfl/remind/tree/restructure_start to avoid a merging mess!

**Comment by merfort** [comment]
Unfortunately yes :/

**Comment by orichters** [comment]
@merfort, @pweigmann: I added a list of all changes done to the scenario config files here: https://github.com/remindmodel/remind/pull/1123#issuecomment-1380362820
So this way, it should be easy to reproduce this change in your PR at some point.

**Comment by orichters** [comment]
`cm_ariadne_VRECapFac_adj` was removed in [this commit](https://github.com/remindmodel/remind/pull/980/commits/9fa21e28a51cdb7d3582fcab1deef4e857e6e98b), can probably be simply deleted. But let people using the config check.

**Comment by mikapfl** [comment]
At the moment, the following tests are still failing:
```
Failure (test_01-readCheckScenarioConfig.R:9): perform readCheckScenarioConfig with 21_regions_EU11/scenario_config_21_EU11_ARIADNE.csv
`readCheckScenarioConfig(csvfile, remindPath = "../../", testmode = TRUE)` generated warnings:
* Unknown column names: cm_biotrade_phaseout

Failure (test_01-readCheckScenarioConfig.R:9): perform readCheckScenarioConfig with 21_regions_EU11/scenario_config_21_EU11_ECEMF.csv
`readCheckScenarioConfig(csvfile, remindPath = "../../", testmode = TRUE)` generated warnings:
* Unknown column names: cm_bioprod_histlim, cm_BioImportTax_EU
* Column name cm_bioprod_histlim in remind settings is outdated. Use more flexible cm_bioprod_regi_lim switch instead, see https://github.com/remindmodel/remind/issues/1157
* Column name cm_BioImportTax_EU in remind settings is outdated. Use more flexible cm_import_tax switch instead, see https://github.com/remindmodel/remind/issues/1157
* Outdated column names found that must not be used.
* 2 errors found.

Failure (test_01-readCheckScenarioConfig.R:9): perform readCheckScenarioConfig with 21_regions_EU11/scenario_config_21_EU11_Fit_for_55_sensitivity.csv
`readCheckScenarioConfig(csvfile, remindPath = "../../", testmode = TRUE)` generated warnings:
* Unknown column names: cm_bioprod_histlim, cm_BioImportTax_EU
* Column name cm_bioprod_histlim in remind settings is outdated. Use more flexible cm_bioprod_regi_lim switch instead, see https://github.com/remindmodel/remind/issues/1157
* Column name cm_BioImportTax_EU in remind settings is outdated. Use more flexible cm_import_tax switch instead, see https://github.com/remindmodel/remind/issues/1157
* Outdated column names found that must not be used.
* 2 errors found.

Failure (test_01-readCheckScenarioConfig.R:9): perform readCheckScenarioConfig with scenario_config_NAVIGATE_300.csv
`readCheckScenarioConfig(csvfile, remindPath = "../../", testmode = TRUE)` generated warnings:
* Unknown column names: cm_bioprod_histlim, cm_BioImportTax_EU, c_BaselineAgriEmiRed, cm_ariadne_VRECapFac_adj
* Column name c_BaselineAgriEmiRed in remind settings is outdated. Use more flexible c_agricult_base_shift switch instead, see https://github.com/remindmodel/remind/issues/1157
* Column name cm_bioprod_histlim in remind settings is outdated. Use more flexible cm_bioprod_regi_lim switch instead, see https://github.com/remindmodel/remind/issues/1157
* Column name cm_BioImportTax_EU in remind settings is outdated. Use more flexible cm_import_tax switch instead, see https://github.com/remindmodel/remind/issues/1157
* Outdated column names found that must not be used.
* 3 errors found.
```

**Comment by orichters** [comment]
Yes, waiting for @fschreyer, @Renato-Rodrigues or @pweigmann to approve [this PR](https://github.com/remindmodel/remind/pull/1184), then we are done.

**Comment by mikapfl** [comment]
* scenario_config_21_EU11_ARIADNE.csv
    * [ ] cm_biotrade_phaseout
* scenario_config_21_EU11_ECEMF.csv
    * [ ] cm_bioprod_histlim
    * [ ] cm_BioImportTax_EU
* scenario_config_21_EU11_Fit_for_55_sensitivity.csv
    * [ ] cm_bioprod_histlim
    * [ ] cm_BioImportTax_EU
* scenario_config_NAVIGATE_300.csv
    * [ ] cm_bioprod_histlim
    * [ ] cm_BioImportTax_EU
    * [ ] c_BaselineAgriEmiRed
    * [ ] cm_ariadne_VRECapFac_adj

**Comment by pweigmann** [comment]
> Yes, waiting for @fschreyer, @Renato-Rodrigues or @pweigmann to approve [this PR](https://github.com/remindmodel/remind/pull/1184), then we are done.

TIL you can ask for your own review. Approved.
