### ISSUE TITLE
regiCarbonPrice not being active breaks scenarios from scenario_config.csv

### ISSUE THREAD

**Issue by merfort** [remindmodel/remind#1245]
Hi all, the switch `cm_implicitQttyTarget` is only working in combination with `regipol = regiCarbonPrice`, right? Because in `scenario_config.csv`  `regiCarbonPrice` is not active for some scenarios, but `cm_implicitQttyTarget` is set. This breaks (probably)
```
SSP2EU-PkBudg500
SSP2EU-PkBudg1150
SSP2EU-EU21-PkBudg500
SSP2EU-EU21-PkBudg1150
```
I observed it for SSP2EU-PkBudg500:
`/p/tmp/merfort/REMIND_development/remind_orig/output/SSP2EU-PkBudg500_2023-03-10_08.26.37`

I guess that `regiCarbonPrice` should be activated in these scenarios, right?

**Comment by Renato-Rodrigues** [comment]
Sorry about that. Your guess is perfect, I forgot to change the switch value when I updated the scenario config two days ago.
I created this PR to fix the issue: https://github.com/remindmodel/remind/pull/1246

**Comment by merfort** [comment]
Thanks for the quick fix!
