### ISSUE TITLE
CES calibration report clean up

### ISSUE THREAD

**Issue by Renato-Rodrigues** [remindmodel/remind#1249]
A question to the demand module experts: @robinhasse , @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q , @robertpietzcker , @johannah-pik , @MariannaR 

As far as I know we calibrate the model based on targets defined at the end nodes of the CES tree.
Please correct me if I am wrong about that, and/or if you define quantity targets for non terminal CES nodes.

Following this assumption, I added some code to the current CES calibration report to filter out non terminal nodes from the industry subsectors realisation. This allows us to have a cleaner calibration pdf report, which include only the entries that matter to focus on.

You can see the code changes in this PR: https://github.com/remindmodel/remind/pull/1248

I would like to ask for each demand module expert to either provide me with a list of CES nodes that should be excluded from the calibration report, or submit a PR to this code changes to include a more comprehensive formulation that includes all demand modules.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> As far as I know we calibrate the model based on targets defined at the end nodes of the CES tree. Please correct me if I am wrong about that, and/or if you define quantity targets for non terminal CES nodes.

No.  Calibration is done on the sets `ppf_29` and `pf_eff_target_dyn37`.

**Comment by Renato-Rodrigues** [comment]
I adjusted the PR filter to use instead the values contained in the two above mentioned sets instead.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Are you aware of #943?

**Comment by Renato-Rodrigues** [comment]
If `fulldata.gdx` is not available, the report should not even run as the calibration should be aborted anyway as it was unsuccessful. 
Besides, the same script has already `fulldata.gdx` dependable lines above the change I made.

Unless there is any chance of the values in the header being different from the values contained on both sets you mentioned before, I would prefer to keep the readGDX alternative instead of the one you provided above. Thank you by the way for the code above!

I think that the linkage between the report filter and the model is much more clear with the gdx reading code, which was the reason in the first place I had to create this issue.

So, if you don't have strong feelings about it, I would keep the current formulation instead.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I can't make myself have strong feelings about REMIND anymore. ;)

The basic point is between short-term fix to get to make the calibration reporting more usable now, and mid-term better calibration reporting.
The other use for the .gdx file is to distinguish between production factors and technologies (`ngcc`, `ngt`, …) that where shoehorned into this file.  I'm not sure they are still needed (i.e. anybody is looking at them), but in any case, there is no need for doing so if the explicit list of production factors to plot from the .csv file is used.
Mid-term I would go for a proper function (for which I have a skeleton lying around) that takes just one file as input to generate the calibration reporting.

**Comment by Renato-Rodrigues** [comment]
I agree 100%, but I still have feelings towards REMIND, even that sometimes they are not that good.
 
Could you then just review the PR as it is now so we have this half baked filter added to the current report?

Hopefully in the near future we will find the time to work on your improved report format.
