### ISSUE TITLE
git version and changes written somewhere in the run?

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#129]
We used to have the SVN/git version and the changes with respect to these reported in the run files, is this not the case any more? It was a very helpful feature.

**Comment by LaviniaBaumstark** [comment]
I think we lost it when moving to git

**Comment by giannou** [comment]
nope, it got lost when someone reworked the start scripts

**Comment by giannou** [comment]
This is of crucial importance when it comes to reproducibility and tractability of published results, and reviewers will want to see it

**Comment by dklein-pik** [comment]
> nope, it got lost when someone reworked the start scripts

If it didn't get lost when moving from SVN to git, but when we reworked the start scripts, one should find the relevant lines of code in the gitlab version of REMIND. But I can't. Can you help me, Anastasi?

**Comment by dklein-pik** [comment]
Found it!

**Comment by dklein-pik** [comment]
Solved with commit 75622a9.
