### ISSUE TITLE
Input data revision number format seems off.

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1345]
> Use at least 4 decimal places for development/testing

https://github.com/remindmodel/remind/blob/f58f505e71fbca03abacbaf7c9b5e584109f9fa7/tutorials/06_Advanced_ChangeInputs.md?plain=1#L44

Nobody used more than three decimal places for eight months
```
$ ll -t /p/projects/rd3mod/inputdata/output/rev*_62eff8f7_remind.tgz | grep -m 1 'rev[0-9]\.[0-9]\{4,\}'
-rw-rw-r-- 1 benke    rdev  81M Oct 20  2022 /p/projects/rd3mod/inputdata/output/rev6.312006_62eff8f7_remind.tgz
```

It is also in contradiction to the information in the preprocessing script (before it was removed)
> ```
> # Current input data revision (<mainrevision>.<subrevision>) ####
> revision <- "6.52"   # should be a number with two decimal places for production
> ```
https://github.com/remindmodel/pre-processing/blob/e79d71c1c49cb9ce3c721b312d3e41708b6c30b2/start.R#L14-L15

So, somebody should decide which it should be, and include that information in the preprocessing script, where people are going to make the actual changes.

**Comment by LaviniaBaumstark** [comment]
fixed in https://github.com/remindmodel/remind/pull/1350
