### ISSUE TITLE
How can a run be restarted, that was interrupted before a fulldata.gdx has been created?

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#140]

**Comment by giannou** [comment]
Was that a bad question? Why was the issue closed? I've had many interrupted runs that I wish to restart but they don't appear in the list because there is no fulldata.gdx in them

**Comment by dklein-pik** [comment]
Oh, sorry. I just fixed this and closed it a bit too early before merging it into the develop branch. Will immedialtely open a pull request. Feel free to review it.

**Comment by giannou** [comment]
ah cool, thanks for the quick response!
