### ISSUE TITLE
set pco and pcc to 0

### ISSUE THREAD

**Issue by orichters** [remindmodel/remind#1400]
- does not seem to be the case now: https://github.com/pik-piam/remind2/issues/378

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
What is not the case?

**Comment by orichters** [comment]
> [But `pcc` should be fixed to 0 in REMIND to avoid confusion (and at some point in the future remove it).](https://github.com/pik-piam/remind2/pull/453#issuecomment-1709579694)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
So there is any point in dragging unused data from one gdx to the next and get new (and old) REMIND used tripped up on it?

**Comment by LaviniaBaumstark** [comment]
solved here: https://github.com/remindmodel/remind/pull/1418#pullrequestreview-1637934832
