### ISSUE TITLE
renv problem with coupled runs

### ISSUE THREAD

**Issue by orichters** [remindmodel/remind#1407]
- This problem exists since some days (maybe related to the rebuild of the renv cache)
- Start a REMIND-MAgPIE run, for example with `./start_bundle_coupled.R config/tests/scenario_config_coupled_shortCascade.csv`
- See, for example `/p/tmp/oliverr/remind/output/C_TESTTHAT-SSP2EU-Base-rem-1`
- The log reads:
```
Results folder output/C_TESTTHAT-SSP2EU-Base-rem-1 already exists containing only log files as expected for coupled runs.
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning: unable to access index for repository
https://rse.pik-potsdam.de/r/packages/src/contrib: cannot open URL
'https://rse.pik-potsdam.de/r/packages/src/contrib/PACKAGES'
   Generating lockfile 'output/C_TESTTHAT-SSP2EU-Base-rem-1/renv.lock'... Error in `submit()`:
! The following package(s) were installed from an unknown source:
               _
  remulator      [1.20.0]
  trafficlight   [1.13.1]

renv may be unable to restore these packages in the future.
```

- One reason only `remulator` and `trafficlight` are affected might be that in the `renv.lock` (see for example `/p/tmp/oliverr/remind/output/TESTTHAT-SSP2EU-Base_2023-09-12_12.53.51/renv.lock`), the `Repository` is stated as `pik`, while it is stated with an URL for `remind2`.
```
    "remulator": {
      "Package": "remulator",
      "Version": "1.20.0",
      "Source": "Repository",
      "Repository": "pik",
...
```
whereas `remind2` looks like that:
```
    "remind2": {
      "Package": "remind2",
      "Version": "1.117.4",
      "Source": "Repository",
      "Repository": "https://rse.pik-potsdam.de/r/packages",
...
```
But, it starts with the definition of `pik`, so it should be able to find it. I did not manage to change the `remulator` Repository to a link.
```
  "R": {
    "Version": "4.1.2",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      },
      {
        "Name": "pik",
        "URL": "https://rse.pik-potsdam.de/r/packages"
      }
    ]
  },
```
Then, I realized that normal REMIND cascades just copy the `renv.lock` in `submit()`, while REMIND-MAgPIE coupling always generates a new one. Probably, because the working directory of REMIND-MAgPIE is the REMIND main folder, while it is the output subfolder for REMIND standalone runs. In any case, [this line](https://github.com/remindmodel/remind/blob/712dec7ec3903272f46a1d97c7fc1c01e9d2f3af/scripts/start/submit.R#L52) seems to evaluate to `TRUE` for every REMIND-MAgPIE run, which I think it shouldn't. And this results in the `renv` code below being executed on the compute nodes which fails, while it works on the login nodes.

As a workaround, I proposed to replace [this line](https://github.com/remindmodel/remind/blob/712dec7ec3903272f46a1d97c7fc1c01e9d2f3af/scripts/start/submit.R#L52) by:
```
if (firstRunInCascade && ! isTRUE(grepl("^C.*-rem-[0-9]+", cfg$title))) {
```
This worked for @tabeado to get her runs done, but this is probably not the right long-term solution.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
The `DESCRIPTION` files of the `remulator` and `trafficlight` packages do not (did not, kind of, see below) contain a `Repository` field
```
$ grep -c Repository renv/library/R-4.1/x86_64-pc-linux-gnu/{remind2,remulator,trafficlight,magclass,mip}/DESCRIPTION
renv/library/R-4.1/x86_64-pc-linux-gnu/remind2/DESCRIPTION:1
renv/library/R-4.1/x86_64-pc-linux-gnu/remulator/DESCRIPTION:0
renv/library/R-4.1/x86_64-pc-linux-gnu/trafficlight/DESCRIPTION:0
renv/library/R-4.1/x86_64-pc-linux-gnu/magclass/DESCRIPTION:1
renv/library/R-4.1/x86_64-pc-linux-gnu/mip/DESCRIPTION:1
```
I suspect that field is added (or not added) by the "CRAN-like" server rse.pik-potsdam.de.

I installed both packages from local directories, which seems to satisfy `renv`.  That should work for now, as both packages seem to get little updates.

But RSE should figure out why these fields are not generated during packaging.  (Might be they are just now and triggering them again will add them.)

**Comment by orichters** [comment]
Ok, thanks for debugging. So this means you have to install them in your renv from local directories to get everything going again? But unclear to me why renv only complains about that on compute node, not on the login node.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> So this means you have to install them in your renv from local directories to get everything going again?

No, should all be in the cache now.

**Comment by orichters** [comment]
Don't know, because
```
cd /p/tmp/oliverr/remind
grep -c Repository renv/library/R-4.1/x86_64-pc-linux-gnu/{remind2,remulator,trafficlight,magclass,mip}/DESCRIPTION
```
still shows the pattern above with remulator + trafficlight missing the Repository field.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> (did not, kind of, see below)

Yes, but now they have 
```
RemoteType: local
RemoteUrl: ~pehl/pik-piam/remulator
```
which seems to suffice for `renv`.

(Also, great that `renv` is not normalising paths.  What could go wrong?)

**Comment by orichters** [comment]
No, I don't, see `less /p/tmp/oliverr/remind/renv/library/R-4.1/x86_64-pc-linux-gnu/remulator/DESCRIPTION`.

Also, `less /p/tmp/oliverr/remind/output/C_TESTTHAT-SSP2EU-Base-rem-1/log.txt` shows the problem persists.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Ah, crap.

`renv` did not put the packages from local source into the cache.  (Which is kind of neat, all things considered.)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
So, `renv::install(c('~pehl/pik-piam/remulator', '`pehl/pik-piam/trafficlight'))` (or any other location where the packages are) should get you (or anyone else) going for now.

**Comment by pfuehrlich-pik** [comment]
What I believe was happening (as you mostly found out already) is that renv tries to figure out where each package was installed from when starting an interactive session or creating a snapshot. If the `Repository` field of the DESCRIPTION does contain a URL, renv is happy and continues. If not, renv tries to fetch all available packages from all configured repositories, and tries to find a repository that offers the package in question - this fails on compute nodes.

**Comment by pfuehrlich-pik** [comment]
The RSE server adds the Repository field as needed by renv for quite some time now, but trafficlight and remulator were apparently built before that. Bumping up the version solved it for the new versions. Installing specifically remulator 1.20.0 would still result in this problem, because the .tar.gz in the archive of the RSE server is still missing the Repository field. there are likely more .tar.gz files in the archive like that, but I believe it is unlikely these older version are used in renv, since we started using renv not too long ago.

**Comment by pfuehrlich-pik** [comment]
For trafficlight 0.13.1 and remulator 1.20.0 specifically I just added the required Repository field to the DESCRIPTION in the global renv cache on the cluster, so these should work now
