### ISSUE TITLE
cm_Industry_CCS_markup implementation broken, not matching definition

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1420]
This https://github.com/remindmodel/remind/blob/548922c8b0ed60e33e69c21b427d20f2f89b16b7/modules/37_industry/subsectors/datainput.gms#L102-L107 for one thing has a syntax error, and for another does not match the definition https://github.com/remindmodel/remind/blob/548922c8b0ed60e33e69c21b427d20f2f89b16b7/main.gms#L1492-L1495

A `cm_Industry_CCS_markup` of 0.66 would not reduce CCS costs in industry by a third, but increase the capture rate at given costs by one halve, possibly exceeding a capture rate of 100 %.

Apparently this was implemented with INNOPATHS.  Is it still required?  Can I clean it up (i.e. cut it)?  Should I fix it?
I need something in between "default" and "no" CCS for industry, so I am checking what I can use or recycle.

**Comment by Renato-Rodrigues** [comment]
As far as I know this is not used anymore, but it would be nice to have, as you mentioned, something in between default and no CCS.
I would leave to you the decision if it is better to do that by fixing this code or by implementing some alternative switch.

I only used this switch in a sensitivity analysis of the results a long time ago, but maybe you should also ask also @fschreyer, as he was the one that implemented this in the remind-eu fork at the first place:
https://github.com/Renato-Rodrigues/remind/commit/b27bb192476db002c99da413af49aa3059a43166#diff-475ac83ca355b537a8b9c25d17290cea6bb65d000e13fdf7df4632520155f4e2R430
