### ISSUE TITLE
allow self-referencing `path_gdx` to restart failed runs?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1423]
Stumbled upon this today
https://github.com/remindmodel/remind/blob/548922c8b0ed60e33e69c21b427d20f2f89b16b7/scripts/start/configureCfg.R#L60-L64
I think it would make sense to allow this self-reference, and go looking for the latest `fulldata.gdx` under the same `scenario` name in order to restart failed runs.  It is easier and less error-prone then copying gdx paths manually.
Thoughts, @orichters?

**Comment by orichters** [comment]
- I would say: Allow it only for `path_gdx`, not for `path_gdx_ref`, `_bau` etc.
- in the first if in the loop, you need another `setdiff` to make sure it doesn't think "ah, this run is newly started, let us make it dependent on it".
```
      if (any(iscen %in% setdiff(iscenarios[iscen, names(path_gdx_list)]), "path_gdx")) {
        stop("Self-reference: ", iscen , " refers to itself in a path_gdx... column.")
      }
      # if a scenario is referenced that is not in the list of scenarios to be started, try to find a gdx automatically
      for (path_to_gdx in names(path_gdx_list)) {
        if (!is.na(iscenarios[iscen, path_to_gdx]) & ! iscenarios[iscen, path_to_gdx] %in% setdiff(row.names(iscenarios), iscen)) {
```
Can you try whether this works?
