### ISSUE TITLE
Unsafe recommendations in Change Inputs tutorial

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1443]
> 5. If the test run completes without errors, add the change in `config/default.cfg` and the update of the input data revision in `main.gms` that was automatically performed by the REMIND run to a commit in your REMIND clone. This can be best done by using 
> ```bash 
> git add -p config/default.cfg main.gms 
> ``` 
> and then selecting the change in `default.cfg` and the first change to the input data in `main.gms` with `y`, and then ignoring possible other changes in `main.gms` with `d`. Create a pull request to push this change to the main REMIND repository, and REMIND will use the new data by default. 

[[↑]](https://github.com/remindmodel/remind/blob/65e63b061aa55e45cfe3d75c5d8af4a1fd23dfbc/tutorials/06_Advanced_ChangeInputs.md?plain=1#L53-L57)

This potentially leads to inconsistencies between input data and CES parameters.  See https://github.com/remindmodel/development_issues/issues/146 and the discussion culminating [here](https://mattermost.pik-potsdam.de/rd3/pl/siygmns9s38ybxca6mb1w1sqmw).
Unless input data has been shown to not affect the calibration results, it should be assumed to require recalibration.

**Comment by fbenke-pik** [comment]
So if I understand you correctly, this is about demanding a recalibration in any case in this tutorial?

Isn't this paragraph basically saying that already?
https://github.com/remindmodel/remind/blob/develop/tutorials/06_Advanced_ChangeInputs.md?plain=1#L51

```
4.a ATTENTION: If your new input data change FE pathways, population, GDP trajectories or substantial behaviour of REMIND, you need to rerun the CES parameter calibration (see tutorial 12_Calibrating_CES_Parameters) and adjust the input data revision together with the updated CES parameters.
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Yes it does.
But it apparently does not work.
