### ISSUE TITLE
Specifying `cfg$output` does not work for coupled runs

### ISSUE THREAD

**Issue by orichters** [remindmodel/remind#1451]
I just noticed that if you specify `output` in your `scenario_config` file which is mapped to `cfg$output` for standalone runs [in configureCfg](https://github.com/remindmodel/remind/blob/develop/scripts/start/configureCfg.R#L39-L42), that does not work in a coupled run. Also means it does not work [in the short cascade](https://github.com/remindmodel/remind/blob/develop/config/tests/scenario_config_shortCascade.csv) of the model tests. There is simply no code in `start_bundle_coupled.R` that does it.

Which makes me think whether we should adjust `start_bundle_coupled.R` such that it also calls `configureCfg` to avoid repeating code (of course, that might need some adjustments here and there).

Actually unrelated, but I would like to have this feature: Specify `cfg$output,fixOnRef` in the `output` column, and then the scripts adds `fixOnRef` to the output scripts defined in `default.cfg`. Should not be _that_ difficult.

**Comment by dklein-pik** [comment]
I will close this issue with PR #1575 but find your ideas regarding `configureCfg` and `cfg$output,fixOnRef` useful and move them to new issues in `development_issues`.
