### ISSUE TITLE
SSP2-PkBudg1100 runs with latest REMIND release crash with division by zero

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#146]
/home/giannou/REMIND/output/SSP2-PkBudg1100_2020-04-13_16.10.08/full.lst

**Comment by giannou** [comment]
the problem seems to be in the calculation of the co2 tax path for peak budget scenarios, so maybe @robertpietzcker can help

**Comment by robertpietzcker** [comment]
I commited a bugfix so that the parameter should always have a value <> 0

**Comment by giannou** [comment]
Thanks so much @robertpietzcker ! Closing the issue now

**Comment by giannou** [comment]
Now the runs don't converge, any hints @robertpietzcker ?
/p/tmp/giannou/sa2_updated/output/PkBudg1100_CDR_2020-04-21_00.50.34

**Comment by giannou** [comment]
fixed with e3965c7
