### ISSUE TITLE
REMIND tests fail on the cluster

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1463]
- [x] `01-readCheckScenarioConfig`
  ```
  Failure (test_01-readCheckScenarioConfig.R:28): readCheckScenarioConfig fails on error-loaden config 
  `w` does not match "13 errors found".
  Actual values:
  yaddayaddayadda 
  * 10 errors found.
  ```
- [x] `01-readCheckScenarioConfig`
  ```
  Failure (test_01-readCheckScenarioConfig.R:45): readCheckScenarioConfig fails on error-loaden config 
  scenConf["PBS", "path_gdx_carbonprice"] not identical to "whitespaceafter ".
  1/1 mismatches
  x[1]: "whitespaceafter"
  y[1]: "whitespaceafter "
  ```
- [ ] `test_01-start.R`
  ```
  Error (test_01-start.R:19): start.R --test startgroup=AMT titletag=AMT config/scenario_config.csv works
  Error: 'with_mocked_bindings' is not an exported object from 'namespace:testthat'
  ```
  There is #1402, but the tests do not source the `.Rprofile`, hence do not run inside the renv
  https://github.com/remindmodel/remind/blob/b6d4e0961143e54d3696e9f7f2641878093bad03/Makefile#L54
  so users are left with whatever was updated whenever in the piam library
  ```
  $ R_PROFILE_USER= Rscript -e "packageDescription('testthat', fields = 'Version')"
  Global .Rprofile loaded! (R version 4.1.2 (2021-11-01))
  0 packages in personal lib '/home/pehl/R/x86_64-pc-linux-gnu-library/4.1'
  see https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/R-packages-on-the-cluster
  [1] "3.1.6"
  ```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> But I cannot reproduce the second part. If I run `make test` after increasing the `testthat` requirement to 3.2.0 (where `with_mocked_bindings` is now considered to be stable), the script tells me:
> 
> ```
> Global .Rprofile loaded! (R version 4.1.2 (2021-11-01))
>   testthat >= 3.2.0 is required, but 3.1.10 is installed - please update: testthat
> Try to fix automatically? (Y/n): Y
> ```
> 
> So somehow `make test` recognizes if the renv is not updated. I think [setup_updateRenv](https://github.com/remindmodel/remind/blob/develop/tests/testthat/setup_updateRenv.R) takes care of that.

It calls `make ensure-reqs`, which will update the packages inside the renv.  But it still does not _use_ the packages in the renv …
```diff
--- a/tests/testthat/test_01-start.R
+++ b/tests/testthat/test_01-start.R
@@ -1,3 +1,10 @@
+test_that(
+    desc = 'testthat is loaded from renv library',
+    code = {
+        expect_match(
+            object = system.file(package = 'testthat'),
+            regexp = paste0('^', Hmisc::escapeRegex(normalizePath('../../'))))
+    })
```
→
```
Failure (test_01-start.R:4): testthat is loaded from renv library
system\.file\(package = "testthat"\) does not match "^/p/tmp/pehl/Remind".
Actual value: "/p/projects/rd3mod/R/libraries/piam_1\.25/4\.1\.2/testthat"
```

**Comment by orichters** [comment]
Ok. I hope @dklein-pik and @pfuehrlich-pik can solve this renv issue…

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
What is the rationale for not using the renv here, anyway?

**Comment by orichters** [comment]
No idea. I suspect that is just an error, but I'm far from being a renv expert.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Looks like Mika wanted to get rid of the beloved "Global .Rprofile loaded! (R version 4.1.2 (2021-11-01))" message. https://github.com/remindmodel/remind/commit/6e486d90c3200d55a0d10e9ddce244715eb14eb0
I guess you can relate …

**Comment by pfuehrlich-pik** [comment]
That is unintentional. I believe R_PROFILE_USER was unset back when renv was not used, so tests are independent of users default `~/.Rprofile`. Thanks for fixing this. I approved https://github.com/remindmodel/remind/pull/1470
