### ISSUE TITLE
fresh REMIND sets up renv with insufficient packages

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1469]
To replicate:
- choose a cosy place on the cluster
- clone REMIND
  ```
  $ cloneremind https://github.com/remindmodel/remind.git ./
  ```
- trigger R to have renv do its setup-dance
  ```
  $ Rscript -e "q()"
  ```
- inspect what was set up
  ```
  $ readlink -e renv/library/R-4.1/x86_64-pc-linux-gnu/testthat
  /p/projects/rd3mod/R/renv_paths_root/cache_1.25/v5/R-4.1/x86_64-pc-linux-gnu/testthat/3.1.6/7910146255835c66e9eb272fb215248d/testthat
  ```

This does not match
```
$ grep testthat DESCRIPTION 
    testthat (>= 3.2.0),
```

**Comment by pfuehrlich-pik** [comment]
`Rscript start.R` detects this and is able to automatically fix it, so I don't think this is critical.
I updated testthat on the cluster, so testthat 3.2.0 is used when bootstrapping the remind renv, so this testthat 3.2.0 specific problem is fixed.
