### ISSUE TITLE
R-package dependency-check does not work, if version does not exist

### ISSUE THREAD

**Issue by sophiefuchs** [remindmodel/remind#1498]
I have updated remind2 version in remind `DESCRIPTION` to v 1.125.0. R package dependency-check `make test` offered to fix version number automatically

```
remind2 >= 1.125.0 is required, but 1.124.0 is installed - please update: remind2
Try to fix automatically? (Y/n):
``` 

However, typing `y` leads to installment of the old version, as the new one does not yet exist (we have not yet merged the new version).

```
Installing remind2 [1.124.0] ...
OK [linked cache]
```

Should instead give an error/warning that the version does not yet exist.

**Comment by pfuehrlich-pik** [comment]
How critical is this? To me it seems rather "nice to have". The case you describe here is not common I'd think.

**Comment by pfuehrlich-pik** [comment]
The dependency check does work, it is just that the newest version is installed for the auto-fix if `>=` is encountered. Setting a dependency on a package version that does not (yet) exist is not a case I'd handle here if there are no specific reasons for it.
