### ISSUE TITLE
AMTs fix on random gdx if AMT they are based on failed

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1540]
https://gitlab.pik-potsdam.de/REMIND/testing_suite/-/blob/a72eb4625634577654cee6f5eaf719c6bdd8a468/README.md#L31-33
```
SSP1-NPi-AMT_2024-02-02_22.09.55                               nash         Abort 11R*5*Infes   5/100             666656666666           6: Intermed Infes    no   no 
SSP1-PkBudg1050-AMT_2024-02-03_14.49.18         4 hours        nash         Normal completion   34/100            converged              2: Locally Optimal   yes  yes
SSP1-PkBudg650-AMT_2024-02-03_14.49.10                         nash         full.log missing    NA                NA                     NA                   no   no 
```
`SSP1-NPi` failed, but `SSP1-PkBudg1050` started from the .gdx file from the calibration
```
/p/projects/remind/modeltests/remind (develop|?? M)$ md5sum ./config/gdx-files/indu_subsectors-buil_simple-tran_edge_esm-POP_pop_SSP1-GDP_gdp_SSP1-En_gdp_SSP1-Kap_debt_limit-Reg_62eff8f7.gdx ./output/SSP1-NPi-AMT_2024-02-02_22.09.55/input.gdx ./output/SSP1-PkBudg1050-AMT_2024-02-03_14.49.18/input.gdx
808fa1380d6b52c44d5cf37ca12830a8  ./config/gdx-files/indu_subsectors-buil_simple-tran_edge_esm-POP_pop_SSP1-GDP_gdp_SSP1-En_gdp_SSP1-Kap_debt_limit-Reg_62eff8f7.gdx
808fa1380d6b52c44d5cf37ca12830a8  ./output/SSP1-NPi-AMT_2024-02-02_22.09.55/input.gdx
808fa1380d6b52c44d5cf37ca12830a8  ./output/SSP1-PkBudg1050-AMT_2024-02-03_14.49.18/input.gdx
```

which contradicts the [documentation](https://github.com/remindmodel/remind/blob/e80dff461f7fe52c5e823e9cd8db193310acd81a/tutorials/03_RunningBundleOfRuns.md?plain=1#L55-L60) and is not really useful (so documentation is OK, behaviour is not)
> These columns starting with `path…` can point to either finished runs or other rows of the current model execution:
> * provide a path to an existing `gdx` file such as `./output/SSP2-Base_2021-12-24_19.30.00/fulldata.gdx`. For subfolders of `./output/`, writing the folder name `SSP2-Base_2021-12-24_19.30.00` is sufficient.
> * provide the entry of a `title` of another row, such as `SSP2-Base`.
>   * If the run with this `title` is set to `start = 1`, then runs that point to this `title` are turned into “subsequent runs“ that will be started after the linked one is finished. Note that in this case, the REMIND code must not change until the `full.gms` file of the last subsequent run was generated.
>   * If the run with this `title` is set to `start = 0` or does not exist in the `scenario_config_XYZ.csv` file, the function `configureCfg` from [`configureCfg.R`](../scripts/start/configureCfg.R) searches in `./output` for folder with that title which contain a `fulldata.gdx` and whose `full.log` states `*** Status: Normal completion`, and then picks the one with the latest date and time in the folder name.
>   * If no run is found, the script also looks in `cfg$modeltests_folder` and so if you use a title of a scenario from the automated model tests in [`scenario_config_AMT.csv`](../config/scenario_config_AMT.csv), the most recent of these run is picked which is useful for testing purposes.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Just realised that the AMTs do not have `path_gdx` defined.  So if more a configuration bug.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
My original argument is valid.  
- `SSP1-PkBudg1050` defines `path_gdx_bau` to be `SSP1-NPi`,
- `SSP1-NPi` failed,
- ergo `SSP1-PkBudg1050` should not run.

**Comment by orichters** [comment]
@dklein-pik implemented that runs that do not actually need a `path_gdx_bau` (because they are not NDC runs) have this dependency removed automatically. So this is not actually an error. https://github.com/remindmodel/remind/pull/1366 Might be worth cleaning up the config files as well, though.
