### ISSUE TITLE
testOneRegi in make test breaks with q37_feedstocksShares

### ISSUE THREAD

**Issue by mellamoSimon** [remindmodel/remind#1597]
It fails with:
```
(...)
**** ERRORS/WARNINGS IN EQUATION q37_feedstocksShares(2150,EUR,segasyn,fegat,ES)
     1 error(s): All Jacobian elements in the row are very small.

**** ERRORS/WARNINGS IN EQUATION q37_feedstocksShares(2150,EUR,sehe,fehes,other)
     1 error(s): All Jacobian elements in the row are very small.

**** ERRORS/WARNINGS IN EQUATION q37_feedstocksShares(2150,EUR,sehe,fehes,ETS)
     1 error(s): All Jacobian elements in the row are very small.

**** ERRORS/WARNINGS IN EQUATION q37_feedstocksShares(2150,EUR,sehe,fehes,ES)
     1 error(s): All Jacobian elements in the row are very small.
```
I'm gonna test Renato's recommended solution:
@mellamoSimon and @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q you most probably would only have to limit the equation `q37_feedstocksShares` to work only in the `sameas(emiMkt,"ETS")` like you probably do for other feedstocks FE equations.

PS: You should also limit the equation only for valid combinations of se and fe used in feedstocks. Above you clearly see that this is not happening as the equation is being defined for `fepet` and `fedie`, which should be transport final energy carriers, and not industrial ones.

_Originally posted by @Renato-Rodrigues in https://github.com/remindmodel/remind/issues/1592#issuecomment-1977130139_

**Comment by mellamoSimon** [comment]
https://github.com/remindmodel/remind/pull/1599 restricts the sets but won't make `testOneRegi` work

**Comment by Renato-Rodrigues** [comment]
You are probably going to need a new calibration run to make the testoneregi work, or test it using as input.gdx of a NPi scenario run.

As you are forcing specific fe shares in the equation `q37_feedstocksShares` , if you don't have a "free" run before for the model to adjust to be compatible with these forced shares, only by merely lucky you would have the case that the original input.gdx file is compatible with your newly forced shares.

**Comment by mellamoSimon** [comment]
I see, thank you! @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q did you run a calibration after introducing that restriction?

**Comment by Renato-Rodrigues** [comment]
I would say that even if he did, it wouldn't matter as before it was including the wrong dimensions by having the sets free.
If the NPi run works, you can go ahead and merge the fix in my opnion.

**Comment by LaviniaBaumstark** [comment]
I will start new calibration runs anyway for the next validation scenarios

**Comment by orichters** [comment]
FYI: `make test` is working again.
