### ISSUE TITLE
dos2unix not directly available on cluster nodes

### ISSUE THREAD

**Issue by johanneskoch94** [remindmodel/remind#172]
Correct me if I'm wrong but, as far as I can tell, the following lines in the prepare function of our starting procedure don't work
```
  # Make sure all MAGICC files have LF line endings, so Fortran won't crash
  if (on_cluster)
    system("find ./core/magicc/ -type f | xargs dos2unix -q")
```

They produce the following error in the log.txt file:

> xargs: dos2unix: No such file or directory

The problem is that the system on the cluster nodes can't find the dos2unix command. We need to add the dos2unix executable to our $PATH (e.g. in /p/projects/rd3mod/tools), or remove the command. (Since it isn't working, as far as I can tell, and nobody is complaining, maybe it isn't necessary?)

**Comment by johanneskoch94** [comment]
I copied the dos2unix executable into /p/projects/rd3mod/tools, and it seems to work. The question remains, if the command is necessary..

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> The question remains, if the command is necessary

Since this apparently didn't work since we moved to the new cluster and REMIND didn't break on that particular issue, I would say no, it is not necessary.  
That being said, I fully expect REMIND to break within three weeks because of DOS line breaks in a MAGICC file :p
