### ISSUE TITLE
Subsequent runs not starting 

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#174]
This run:
`/p/tmp/giannou/sa2_updated/output/NDC_spvL_CDR_2020-05-12_20.12.24`
has 3 subsequent runs: 
`$subsequentruns
[1] "PkBudg1100_spvL_CDR" "PkBudg900_spvL_CDR"  "PkBudg1300_spvL_CDR"`
They weren't started when the run was finished and they don't start when I restart the basis-run with
`Rscript start.R --restart` from the mail folder. 
Any idea what is going on here? I get no error message and in the `log.txt` file it looks as though the subsequent runs don't exist.

Other runs of mine had the same problem.

**Comment by giannou** [comment]
Ok I think I have an idea what is causing the problem. When a run is preempted, once (automatically) restarted the presence of `full.gms` in the run folder makes the `prepare_and_run.R`script think that it is a run that is being restarted manually and sets the object `start_subsequent_runs`object to `FALSE`

We might want to fix this

**Comment by johanneskoch94** [comment]
This is the specifically set behavior. When restarting a run subsequent runs are not started. Because it doesn't work, or because one doesn't want to do this by default, I don't know. Try changing the flag in line the prepare_and_run.R script.

**Comment by johanneskoch94** [comment]
Oh sry... didn't see your comment ;)

**Comment by LaviniaBaumstark** [comment]
I think for restarted runs we really do not want to also restart the subsequent runs. But for automatically preempted runs we would like to also start the subsequent runs. There is an option to run a few scripts before a run is preempted. Maybe this could be handed there.
