### ISSUE TITLE
dependency problem on Mac: regionscode function not found

### ISSUE THREAD

**Issue by jeh0753** [remindmodel/remind#252]
Installing the latest R version, GAMS version, and following the documentation through on Mac brings the following error when running `source('start.R')`: 

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1597013/94822730-fac18700-03d0-11eb-8679-696b6fb23b20.png">

I've recreated this on two separate Mac machines. If I'm able to sort it out I'll post here, but any ideas or solutions would be a great help.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
You are missing the [`moinput` package](https://rse.pik-potsdam.de/r/packages/src/contrib/moinput_9.345.0.tar.gz), which imports the [`madrat` package](https://rse.pik-potsdam.de/r/packages/src/contrib/madrat_1.83.4.tar.gz), which provides `regionscode()`.
