### ISSUE TITLE
add job type selection for scenario comparisons and other improvements

### ISSUE THREAD

**Issue by Renato-Rodrigues** [remindmodel/remind#315]
After you select:
Rscript output.R > 2: Comparison across runs > 9: compareScenarios > and choose the scenario to be compared

It would be important to have the two following questions asking for additional user input:

(1) Please provide a file name prefix (press enter to none):

If the user type any string, this should be added to the beginning of the comparison scenario filenames. This is highly important when creating multiple comparison scenarios simultaneously.

(2) Please choose the SLURM configuration for your submission (default: priority):

options: 
1: SLURM priority
2: SLURM standby 
 
This is highly important because the cluster is taking too long in the standby queue. If you are creating reportings by hand, there is a higher chance that this is one of your priorities.

**Comment by amnmalik** [comment]
I have a few suggestions:
1. Currently, _short_ until 2050 and _long/normal_ until 2100 are automatically produced, could we have other arguments that are part of the function remind2:compareScenarios(), allowing to have specific years, regions etc.?
2. Some comments/description on the various options after executing `Rscript output.R` would be very useful.

**Comment by Renato-Rodrigues** [comment]
About 1, this is already support in the parameters: 

- y = c(seq(2005, 2060, 5), seq(2070, 2100, 10))
- y_hist = c(seq(1960, 2020, 1), seq(2025, 2100, 5))
- y_bar = c(2010, 2030, 2050, 2100)
- reg = NULL
- mainReg = "GLO"

**Comment by amnmalik** [comment]
True, but they are not available in the routine you mentioned : Rscript output.R > 2: Comparison across runs > 9: compareScenarios > and choose the scenario to be compared, or where can they be entered?

**Comment by Renato-Rodrigues** [comment]
yeah, but the Rscript output.R is just including the most common uses for the reporting. 
If you want a specific configuration you should run the function instead.

I am not saying that more flexibility couldn't be added to it if there is enough use cases and user requests to justify them, but I would put this request in a different group from the ones I mentioned in the first message.

**Comment by giannou** [comment]
You can change the configuration of the R function in `scripts/output/comparison/compareScenarios.R`, no?
