### ISSUE TITLE
Green, blue, gray hydrogen

### ISSUE THREAD

**Issue by kais-siala** [remindmodel/remind#344]
**Status:**
Right now, there is a variable in REMIND (v_shGreenH2) that defines the share of green hydrogen as all the hydrogen produced from electricity.

**Issues:**
- Hydrogen produced from biomass (bioh2) should be considered green
- We might be using the "green label certificates" multiple times (now we are only interested in producing H2, but there might be other uses in the future)
- We do not count blue and gray hydrogen (counting those is actually straightforward, so no big issue)

**Propositions:**
1. Quick fix: add the H2 produced by biomass to the left hand side of the equation q_shGreenH2
2. Force electrolyzers to only use electricity from renewable energy technologies, for example by using another fuel seelRE that is consumed by them or by a dummy process converting 1:1 seelRE into seel.
3. It might make sense to define new fuels (seh2green, seh2blue, seh2gray) to simplify the accounting (not necessary)

**Comment by fschreyer** [comment]
Hi Kais!

I see your point. The label "green" is vague here. At the moment this share calculation of ``v_shGreenH2`` serves only to be able to force the model to produce all or large amounts of H2 from electricity. Adapting this, we should make sure that people using the switch ``c_shGreenH2`` can still run scenarios with mostly electrolysis H2. Easiest solution is in my view to create a share of electric (e.g. ``v_shElH2``) and a share of electric+bio H2 and control both by scenario switches.

What is the background of this change? What would you like to do with more categories for hydrogen in the model? Is it about force or constrain electric+biogenic H2 in certain scenarios or calculating other parameters from this? In our reporting we have a finer resolution of hydrogen in the variables ``SE|Hydrogen|Biomass``, ``SE|Hydrogen|Electricity``, ``SE|Hydrogen|Gas`` etc.
Best,
Felix
