### ISSUE TITLE
Author Initials in GAMS Comments?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#345]
> - Start comment on sections with the initials of the programmer and the data of change (e.g. GL, 2011-06-07)

https://github.com/remindmodel/remind/blob/develop/tutorials/7_Advanced_ChangeCode.md

Nobody is doing that anymore, now most people now how to use git blame (at leas on github), right?  Should we scrap that?

**Comment by LaviniaBaumstark** [comment]
agree and will adjust it with my nest commit

**Comment by LaviniaBaumstark** [comment]
changed
