### ISSUE TITLE
unresolvable dependency in downscalescript.R and downscalefct.R

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#357]
https://github.com/remindmodel/remind/blob/c7d37827f341b155544f7ef476ecfea5639ea2d3/scripts/output/single/downscalescript.R#L18

https://github.com/remindmodel/remind/blob/c7d37827f341b155544f7ef476ecfea5639ea2d3/scripts/output/single/downscalefct.R#L18

There is no package `ncdf`.

```
> download.packages('ncdf', './')
Warning in download.packages("ncdf", "./") :
  no package 'ncdf' at the repositories
     [,1] [,2]
> getOption('repos')
                                   CRAN                                     pik 
             "https://cran.rstudio.com" "https://rse.pik-potsdam.de/r/packages" 
```

**Comment by orichters** [comment]
files were deleted
