### ISSUE TITLE
missing files.txt leads to missing files

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#365]
https://github.com/remindmodel/remind/blob/d6cd0316a599ea328b42c355f3472339c9cc2093/modules/24_trade/se_trade/datainput.gms#L19

None of these will work unless there is a `./modules/24_trade/se_trade/input/files.txt` file telling `prepare_and_run.R` where to copy the input files.

**Comment by Renato-Rodrigues** [comment]
fixed by https://github.com/remindmodel/remind/commit/4d90bd83edd5ea5b33bd1ff22312087252d0c42e
