### ISSUE TITLE
MAGICC still "temporarily" disabled in reporting

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#368]
https://github.com/remindmodel/remind/blob/4d90bd83edd5ea5b33bd1ff22312087252d0c42e/scripts/output/single/reporting.R#L38-L53 from 01f5e80

**Comment by Renato-Rodrigues** [comment]
I don't know enough about MAGICC to do anything about this issue.
Whom would be the person that "created"/"know anything" about the MAGICC reporting to correct assign this to somebody that could test and fix if necessary any issue?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Maybe me.
Do you remember what the problem was?

**Comment by Renato-Rodrigues** [comment]
I am sorry, but no. 
At the time, and also just before the merge, I disabled some reportings that were not working with REMIND-EU and the bio/fossil splits as I had no way to fix them all by myself in time. 
Some of them were re-enabled after some tests, but I never got the chance to even retest this one.
Maybe it is just a matter of re-enabling it and see if it just magically works, or changing some variable naming, but I am really not sure without spending some time testing it.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Will be testing then.  Nobody objected so far, so it doesn't seem to be urgent :p
