### ISSUE TITLE
missing file paths crash REMIND

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#371]
https://github.com/pik-piam/mrremind/blob/3a86f4fccc387fb82b1e2417e41b6f0b7a09c631/R/fullREMIND.R#L89-L90
```
  calcOutput("PotentialWindOn",                       round=3,  file="f_maxProdGradeRegiWindOn.cs3r")
  calcOutput("PotentialWindOff",                      round=3,  file="f_maxProdGradeRegiWindOff.cs3r")
```
from [`a402506`](https://github.com/pik-piam/mrremind/commit/a402506b0b51935f3917a01705734a4280b61e67) and [`7b2a66d`](https://github.com/pik-piam/mrremind/commit/7b2a66dfa122b478d0a241795554eccf7be3f53b), respectively, also require an update to https://github.com/remindmodel/remind/blob/cce73c4362abace0702584bcc3afc67c51452fec/core/datainput.gms#L640-L644 as well as https://github.com/remindmodel/remind/blob/cce73c4362abace0702584bcc3afc67c51452fec/core/input/files#L12 to take effect.

**Comment by Renato-Rodrigues** [comment]
@cchrisgong @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q 
Can we close this issue? I think it is fixed already, no?

**Comment by cchrisgong** [comment]
yes this is fixed, sorry
