### ISSUE TITLE
a fallback option is needed here in case the defined GDX is not available 

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#377]
https://github.com/remindmodel/remind/blob/6cc4d70d97b14a7670c9a4617cd291395925794c/scripts/start/prepare_and_run.R#L430

Which GDX should be taken as a "generic" one? Something like the old `input.gdx`.
Tagging @MariannaR

**Comment by LaviniaBaumstark** [comment]
I am not sure whether we want to have a fallback gdx. If this one is really bad for the scenario it would lead to long time waiting for the scenario and no information that the fallback gdx was used. I would prefer a stop if the expected gdx is missing. I the user wants to get the scenario started, he/she could provide a gdx-path in the scenario_config

**Comment by giannou** [comment]
Fine with me. If Marianna is also fine and found a solution to the issues she was facing today the present issue can be closed.

**Comment by MariannaR** [comment]
It is also fine with me! I discussed with Lavinia and realized I made a mistake in the config file, and this was the reason I had problems starting the run.
