### ISSUE TITLE
New reporting brakes NDC runs

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#378]
https://github.com/remindmodel/remind/blob/6cc4d70d97b14a7670c9a4617cd291395925794c/scripts/input/prepare_NDC2018.R#L30

Is there a mapping old->new emission variables? What should this variable be replaced with?

**Comment by fschreyer** [comment]
Wow ok! :) Well, we have many variables but this specific one we do not have yet. I will quickly add it to the library.

**Comment by giannou** [comment]
This is kinda urgent, by the way ;)

**Comment by giannou** [comment]
Thanks for reacting so quickly! By the way, we could consider adding this script as well as the exoGAINS one to the tests of the remind2 R library

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
[Still broken](https://github.com/remindmodel/remind/pull/379/files/fb2a72c1766d641cf306bfb61704b261b61b5405#diff-1ac49ee16ab42d37668c20788e51e7c7f91b16a136e3c233624fe241ec0807e7) @fschreyer.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> [Still broken](https://github.com/remindmodel/remind/pull/379/files/fb2a72c1766d641cf306bfb61704b261b61b5405#diff-1ac49ee16ab42d37668c20788e51e7c7f91b16a136e3c233624fe241ec0807e7) @fschreyer.

I have to pay more attention on who is doing what in these pull requests.  Sorry, again, @fschreyer!

[Still broken](https://github.com/remindmodel/remind/pull/379/files/fb2a72c1766d641cf306bfb61704b261b61b5405#diff-1ac49ee16ab42d37668c20788e51e7c7f91b16a136e3c233624fe241ec0807e7) @giannou

**Comment by giannou** [comment]
Do you have an example of a run that didn't work?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
No.  But the code doesn't do what it apparently is supposed to do – checking whether the variable `Emi|GHG|w/o Land-Use Change` is available.  You don't need a run to see that.
