### ISSUE TITLE
additional support for "pluses" uses in variable definitions

### ISSUE THREAD

**Issue by Renato-Rodrigues** [remindmodel/remind#388]
Two suggestions for possible enhancements:

1. More grouping alternatives:

Currently we are limited to two (or three?) variable groups for aggregation checking using + and ++ (is it +++ supported?).

My suggestions:

- Support the use of strings after a plus to define alternative groups = "var|_**+%string%**_|var" -> var|var 
Ex: 
  - Emi|CO2|_**+**_|Energy         + Emi|CO2|_**+**_|Process              = Emi|CO2
  - Emi|CO2|_**++**_|ETS            + Emi|CO2|_**++**_|ESR                  = Emi|CO2
  - Emi|CO2|_**+type**_|Gross    + Emi|CO2|_**+type**_|Negative     = Emi|CO2
  - Emi|CO2|_**+geo**_|Bunkers + Emi|CO2|_**+geo**_|w/o Bunkers = Emi|CO2
- Advantage of the proposal, it can be backwards compatible with the current plus use and it allows a more extensive variables checking.

 2. Subtraction support:
- Support the use of a negative sign to subtract variables from groups = "var|_**-%string%**_|var" -> var|var 
Ex: 
  - Emi|CO2|+type|Gross _**-**_ Emi|CO2|_**-type**_|CDR = Emi|CO2
- Advantage of the proposal: it avoids the need to define the same variable twice, one with negative values, and another with positive values if they are used in different aggregations, like for example, CDR being used in carbon management (as a positive value), and in a gross net emissions reporting (as a negative value).

**Comment by giannou** [comment]
- The tool can handle more than +++: https://github.com/pik-piam/mip/blob/967640d36e2396d0f6aeef2b05d807eaf97cc8a8/tests/testthat/test-extractVariableGroups.R#L19
It actually can go up to 10. 
- I agree about the `-` sign, not sure how easy this will be to program though. 
- The +type seems a bit of an overkill to me, will be difficult to implement and make the variables hard to read.

**Comment by Renato-Rodrigues** [comment]
@giannou 
Thk you for the quick reply!

Just a quick reaction, I don't think it is worst to read this:
- Emi|CO2|+geo|Bunkers
than this:
- Emi|CO2|+++++|Bunkers

Besides, it avoids mistyping the number of pluses, and it is easier (in my opinion) to know the variables that are group together at first sight without counting pluses for each one of them.

But I certainly agree that if it is difficult to implement, and as you clarified above sequential pluses are already supported, if there is ever a decision in favor of implementing this alternative approach it should be considered a lower priority for now.

Thank you!

**Comment by giannou** [comment]
When you have hundreds of variables listed in front of you I think it's easier for the eye to categorize according to symbols to identify summation groups and according to words to identify all the rest. But maybe that's my interpretation. It's in any case a good suggestion and if the group wants it I'm happy to implement it!
