### ISSUE TITLE
race condition while copying MAGICC to core breaks REMIND runs

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#392]
https://github.com/remindmodel/remind/blob/4d90bd83edd5ea5b33bd1ff22312087252d0c42e/scripts/start/prepare_and_run.R#L234-L248

If several runs are started simultaneously (i.e. almost always), they all copy MAGICC to `./core/magicc/` at the same time, resulting in a race condition that can leave individual MAGICC files empty or incomplete, crashing MAGICC and REMIND later on.

Copying MAGICC should be moved inside the lock to prevent this, or should be copied to the output directory directly.

**Comment by giannou** [comment]
hopefully solved via https://github.com/remindmodel/remind/pull/429
