### ISSUE TITLE
File removal crashes scenarios with "climate" = "magicc"

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#427]
The removal of the file `magicc_scen_bau.inc` (https://github.com/remindmodel/remind/commit/704f3333d001bb9729519c498b0615ccc3abe778) makes starting of runs with realization "magicc" of module "climate" impossible. Was there a reason why this was not taken into consideration?

**Comment by LaviniaBaumstark** [comment]
I do not know and I do not see any reason why not adding it back

**Comment by giannou** [comment]
solved via https://github.com/remindmodel/remind/pull/429
