### ISSUE TITLE
This line causes a "division by 0" fatal error in the first model iteration 

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#455]
https://github.com/remindmodel/remind/blob/81a44f1e88891f5dd957aca518f30e5a02c0f028/core/postsolve.gms#L671

This has to be fixed asap as it appears already in the baseline SSP2 case which means no further run can be performed. Maybe perform test runs before committing changes?

**Comment by cchrisgong** [comment]
I performed test runs without problem. The conditional "$(v_costInvTeDir.l(ttot,regi,te) ne 0)" should ensure no division by 0 error occurs?

**Comment by giannou** [comment]
fixed in b3c9e6b8a834913aabebb9021da299919ca92c8c
