### ISSUE TITLE
This commit breaks testOneRegi runs (infes in q_qap)

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#458]
..and potentially also other configurations.

Has it been properly tested? https://github.com/remindmodel/remind/commit/7f4699f5561ff4dbaf70c9de7ee68d226d1eea6d

Maybe a different GDX will help, can you provide one if this is the case?

**Comment by Loisel** [comment]
Oh I see. Maybe revert for now, I'll test again. I *did* test it some time ago and I don't remember, sorry for this. Maybe there was a reason I did not merge back then...

**Comment by Loisel** [comment]
See PR #459
