### ISSUE TITLE
question on path_gdx_bau

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#62]
`path_gdx_bau` is not included in the default configuration
https://github.com/remindmodel/remind/blob/46de32775ed14828d0a095a80c18e508d3cce8d5/config/scenario_config.csv#L1
which gives a bothersome warning in `start.R`
https://github.com/remindmodel/remind/blob/46de32775ed14828d0a095a80c18e508d3cce8d5/start.R#L84
```
Warning messages:
1: In is.na(isettings$path_gdx_bau) :
  is.na() applied to non-(list or vector) of type 'NULL'
```
Shouldn't it be included in the default configuration (even if empty)?

**Comment by orichters** [comment]
solved a while ago in master: https://github.com/remindmodel/remind/commit/0a40bd07ab08b8d7a703de7857ceff62de6f8c2b#diff-188e9ba397847d5614e55ff91550cb1b0ae63dba3e746c945e48baec4b52ff72

file is deleted in develop
