### ISSUE TITLE
c_GDPpcScen flag crashes code

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#7]
![Screenshot 2019-12-10 16 17 18](https://user-images.githubusercontent.com/11047746/70542229-aced4100-1b68-11ea-8b68-4741a3f19c4b.png)

**Comment by giannou** [comment]
fixed temporarily with #8 but the problem has to be solved for the long run

**Comment by LaviniaBaumstark** [comment]
fixed

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@giannou in case this is still relevant: 
> ![Screenshot 2019-12-10 16 17 18](https://user-images.githubusercontent.com/11047746/70542229-aced4100-1b68-11ea-8b68-4741a3f19c4b.png)

`=` is not an assignment operator, but test numerical equality.
```
$if %cm_GDPScen% == "gdpSSP1" $setglobal c_GDPpcScen "SSP1"
```
should work.
