### ISSUE TITLE
missing R dependencies for installing REMIND

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#76]
https://github.com/remindmodel/remind/blob/23fc5eb1677378dc2247839c886ac1417eab9c71/tutorials/1_GettingREMIND.md#L30-L45
This fails, because `remind` depends on `remulator`, depends on `magpie4`, depends on `moinput`, depends on `rhdf5`.  So the Bioconductor-stuff is needed as well.

**Comment by dklein-pik** [comment]
Oh yeah, thank you! Do you want to add it to the tutorial or should I?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Better if you do it.  I always get annoyed by Bioconductor. :p

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Also
https://github.com/remindmodel/remind/blob/23fc5eb1677378dc2247839c886ac1417eab9c71/tutorials/1_GettingREMIND.md#L50-L62

Don't know about Windows systems, but on Linux, `which` will not return an error if it doesn't find a program.  So if `pdflatex` is not on the path, there will be no error.  I would suggest using
```
system('pdflatex -version')
```
instead.
