### ISSUE TITLE
CDR=off copies DAC capacities from input.gdx

### ISSUE THREAD

**Issue by chroetz** [remindmodel/remind#816]
If DAC is off (CDR=off or CDR=weathering), the capacity values of DAC `vm_cap` and `vm_capCum` of the input.gdx are copied to the fulldata.gdx. 

Usually, this is not a big problem as most gdx-files used for the starting point (input.gdx), have DAC capacities close to 0. But if one uses an input.gdx with a high DAC capacity on a CDR=off run, the output will also show the high DAC capacity, which is counter-intuitive to CDR=off. Furthermore, direct dependence of the optimization result on the starting point like this should be avoided.

Fixing this may not be as simple as setting vm_cap to 0 for DAC as this may render [`q_capCumNet`](https://github.com/remindmodel/remind/blob/2317b01a253ad69438d68a7145b18a24f93e6707/core/equations.gms#L371)  infeasible.
See #713 and #789.

**Comment by orichters** [comment]
Maybe, @katarkow, you can have a look?

**Comment by orichters** [comment]
CDR=off does not exist anymore.

**Comment by orichters** [comment]
CDR=off does not exist anymore.
