### ISSUE TITLE
REMIND default broken because of unused argument in EDGE-T

### ISSUE THREAD

**Issue by orichters** [remindmodel/remind#818]
The default run in REMIND is currently broken with this error message:
```
Error in shares_intensity_and_demand(logit_shares = shares, MJ_km_base = mj_km_data,  : 
  unused argument (EDGE2CESmap = EDGE2CESmap)
```
A short `reposearch` leads me to [this commit](https://github.com/pik-piam/edgeTrpLib/commit/66265eec00fcc735423351d21b90620d287d6c8a) by @Loisel that probably has caused this. Would be appreciated if you could fix it on the REMIND side. Thanks!

May be it is worth discussing with RSE (@pfuehrlich-pik, @mikapfl) about adding a test to the package that checks whether [remindmodel / EDGE_transport.R](https://github.com/remindmodel/remind/blob/develop/scripts/iterative/EDGE_transport.R) works.

**Comment by pfuehrlich-pik** [comment]
This is fixed by #819, right @MariannaR ?

**Comment by MariannaR** [comment]
yes, this is fixed.

**Comment by orichters** [comment]
Thanks for fixing it!
