### ISSUE TITLE
model lock conflicts

### ISSUE THREAD

**Issue by orichters** [remindmodel/remind#841]
The problem: Both in REMIND and MAgPIE, sometimes, the lock via [gms/model_lock](https://github.com/pik-piam/gms/blob/master/R/model_lock.R) does not work properly and two runs operate simultaneously on gms files or input data, causing failed runs and [wrong data](https://github.com/magpiemodel/magpie/issues/395).

Experience by @dklein-pik, @giannou and @orichters shows it happens mostly when subsequent runs were started, but it was difficult to find a working example that consistently reproduces the behavior. Maybe a parallel cluster hiccup is needed.

- [x] We already [improved the error message in the gms package](https://github.com/pik-piam/gms/pull/17) if something goes wrong with the locking mechanism.
- [ ] For coupled runs, in [this PR](https://github.com/remindmodel/remind/pull/835), I suggest to @dklein to add a sleep of 10 seconds between starting subsequent runs (where we had this problem) to see whether this helps, but we may wish to use it consistently also in the initial start phase and for standalone runs.
- [ ] An alternative could be not to use self-chosen numbers in the model_lock, but rather use some combination of run title with an id or so such that at least all the runs fail instead of thinking everything was fine, but this does not solve the problem, only makes fails more transparent.
- [ ] @mikapfl suggested to eliminate (almost all) locking, which is some work, but maybe worth it given how hard locking is in general and in particular in distributed file systems
- [ ] @mikapfl suggested to use NFS-safe locking which uses hardlinks to lock files because making a hardlink is a guaranteed atomic operation by POSIX, but this requires collision-resistant IDs, like e.g. UUIDs or whatever. Scenario names are not collision-resistant.

**Comment by mikapfl** [comment]
shouldn't this be a bug in the gms package?

**Comment by orichters** [comment]
ok, moved to https://github.com/pik-piam/gms/issues/19 (there does not seem to be a way to move it to another repo in a different organisation)
