### ISSUE TITLE
asked for Negishi, scripts start Nash

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#86]
![Screenshot 2020-03-02 12 41 33](https://user-images.githubusercontent.com/11047746/75673593-9f38ea80-5c83-11ea-9407-1b4608b6e92b.png)

**Comment by johanneskoch94** [comment]
Hey :) I don't think it works that way... The '12' you enter just sets some slurm flags.. ("--qos=medium --nodes=1 --tasks-per-node=1" in this case...) it doesn't configure the run. Are you sure that your config file shows negishi?

**Comment by giannou** [comment]
OMG you're right, I just noticed that my config doesn't have the Negishi flag activated. Thanks a lot, I'm closing the issue
