### ISSUE TITLE
createRDS() does not exits anymore

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#945]
https://github.com/remindmodel/remind/blob/bea73f0002ff2d587a46489751cbc21f9b6a083b/scripts/iterative/EDGE_transport.R#L65
will break REMIND because [`edgeTransport` got stuff renamed](https://github.com/pik-piam/edgeTransport/commit/ca05f0214e3cc819ab4243cf6f649d072668eb72#diff-b6b6854a02ae177f8860f49654ff250c1554d021ae434b6efdbe99d00bdc6055).

Assigning @johannah-pik because @Loisel is on vacation I gather

**Comment by johannah-pik** [comment]
https://github.com/remindmodel/remind/pull/932/files this PR includes the change to a new iterative script integrated in the edgeTransport package. The new script should be fully functional with the new naming scheme

**Comment by johannah-pik** [comment]
So the one you are referring to is no longer used

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I see.  Maybe remove the unused script, then.
