### ISSUE TITLE
after rerunning REMIND reporting, MAgPIE results are missing

### ISSUE THREAD

**Issue by orichters** [remindmodel/remind#988]
After each REMIND iteration, `start_coupled.R` [writes the MAgPIE data into the REMIND mif file](https://github.com/remindmodel/remind/blob/727dd53fef47ca4b98f09d4ce5f342ddb1393f13/start_coupled.R#L200-L224). But if you rerun the REMIND reporting, you lose this information, and `compareScenarios2`, the export with [`xlsx_IIASA`](https://github.com/remindmodel/remind/blob/develop/scripts/output/export/xlsx_IIASA.R) and every other scripts fail to find the data.

An alternative option I could imagine is for the reporting to check whether the file in `cfg$pathToMagpieReport` exists and always add that content directly to the `.mif` file. Further ideas?

**Comment by dklein-pik** [comment]
Good idea. If `cfg$pathToMagpieReport` exists, REMIND has been started using MAgPIE data from this report, so why not always append the corresponding MAgPIE report. However, the code in `start_coupled.R` you cited above and that currently appends the MAgPIE report to the remind report should then be removed.

**Comment by merfort** [comment]
Sounds like a neat solution. Moving the concatenation of reportings to the reporting procedure itself seems to be very natural.
